<?php



return array(
    'object_types' => [ 
        1  => "Personenlift", 
        2  => "Huisliften", 
        3  => "Magazijnlift",
        4  => "Goederenlift", 
        5  => "Hefplatformlift", 
        6  => "Autolift",
        7  => "Keukenlift", 
        8  => "Beddenlift", 
        9  => "Platform",
        10 => "Hefplateau of plateaulift", 
        11 => "Gevellift", 
     ],

     'check_types' => [ 
        1 => "Opleveringskeuring", 
        2 => "Eerste keuring na ingebruikname", 
        3 => "Periodiekekeuring",
        3 => "Herkeuring" 
    ],
   
    'incident_types' => [ 
        1 => "Extern", 
        2 => "Interieur" ,
        3 => "Mechanische",
        4 => "Elektrische", 
        5 => "Deuren",
        6 => "Bediening",
       
    ],
    
    'building_access_types' => array(
        1 => "Tag", 
        2 => "Code", 
        3 => "Sleutel" ,
        4 => "Geen"
    ),

    'building_types' => array(
        0  => 'Onbekend',
        1  => 'Appartementen',
        2  => 'Appartementencomplex',
        3  => 'Arbeiderswoning',
        4  => 'Aula',
        5  => 'Bankgebouw',
        6  => 'Bedrijfsgebouw',
        7  => 'Bedrijfsgebouw met woning(en)',
        8  => 'Begeleid wonen',
        9  => 'Begraafplaats',
        10 => 'Bejaardentehuis, verzorgingstehuis',
        11 => 'Bibliotheek',
        12 => 'Bioscoop',
        13 => 'Boerderij',
        14 => 'Boven- en benedenwoningen',
        15 => 'Brouwerij',
        16 => 'Brug',
        17 => 'Bungalow',
        18 => 'Crematorium',
        19 => 'Dienstgebouw',
        20 => 'Eengezinswoning',
        21 => 'Eengezinswoning in een rij',
        22 => 'Expositiegebouw',
        23 => 'Galerijflat',
        24 => 'Galerijflat met bedrijfsruimte',
        25 => 'Galerijwoningen',
        26 => 'Gasthuis',
        27 => 'Gerechtsgebouw',
        28 => 'Gevangenis',
        29 => 'Handelsgebouw',
        30 => 'Herenhuis',
        31 => 'Hotel-restaurant',
        32 => 'Industriegebouw',
        33 => 'Instelling',
        34 => 'Jongerenhuisvesting',
        35 => 'Kantoorgebouw',
        36 => 'Kerkgebouw',
        37 => 'Kerktoren',
        38 => 'Kinderopvang',
        39 => 'Kiosk',
        40 => 'Koetshuis',
        41 => 'Landhuis',
        42 => 'Mantelzorgwoningen',
        43 => 'Militair gebouw',
        44 => 'Multifuctioneel woongebouw',
        45 => 'Museumgebouw',
        46 => 'Nutsgebouw',
        47 => 'Onderwijsgebouw',
        48 => 'Opbouw',
        49 => 'Openbaar toilet',
        50 => 'Overheidsgebouw',
        51 => 'P+R voorziening',
        52 => 'Pakhuis',
        53 => 'Parkeergebouw',
        54 => 'Patiowoningen',
        55 => 'Patriciërshuis',
        56 => 'Politiebureau',
        57 => 'Pompgebouw, gemaal, sluis',
        58 => 'Pompstation',
        59 => 'Portiekflat',
        60 => 'Portiekwoningen',
        61 => 'Recreatieve voorziening',
        62 => 'Religieus gebouw',
        63 => 'Rentenierswoning',
        64 => 'Restaurant',
        65 => 'Rijwoningen',
        66 => 'Schoolgebouw (50)',
        67 => 'Schouwburg',
        68 => 'Seniorenwoningen',
        69 => 'Sportgebouw',
        70 => 'Stadsvilla (12)',
        71 => 'Startersappartementen',
        72 => 'Stationsgebouw',
        73 => 'Straatmeubilair',
        74 => 'Studentenwoning',
        75 => 'Theehuis',
        76 => 'Tuinhuis',
        77 => 'Tuinkoepel',
        78 => 'Twee-onder-een-kapwoning',
        79 => 'Universiteitsgebouw',
        80 => 'Verenigingsgebouw',
        81 => 'Villa',
        82 => 'Vrijstaande woning',
        83 => 'Warenhuis',
        84 => 'Watertoren',
        85 => 'Weeshuis',
        86 => 'Wijkvoorzieningsgebouw',
        87 => 'Winkel',
        88 => 'Winkelcentrum',
        89 => 'Winkelwoningcomplex',
        90 => 'Woningen',
        91 => 'Woon- werkgebouw',
        92 => 'Woonhuis',
        93 => 'Woonstudio',
        94 => 'Ziekenhuis',
        95 => 'Zorginstelling',
        96 => 'Zwembad'
    
    ),

);